"
class
"
Class {
	#name : 'Vacuna',
	#superclass : 'Object',
	#instVars : [
		'nombre',
		'laboratorio',
		'especieDestino',
		'mesesVigencia'
	],
	#category : 'tp-final-poo',
	#package : 'tp-final-poo'
}

{ #category : 'accessing' }
Vacuna >> especieDestino [

	^ especieDestino
]

{ #category : 'accessing' }
Vacuna >> laboratorio [

	^ laboratorio
]

{ #category : 'accessing' }
Vacuna >> mesesVigencia [

	^ mesesVigencia
]

{ #category : 'accessing' }
Vacuna >> nombre [

	^ nombre
]
